<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\YiLocal.Core\YiLocal.Core.csproj" />
    <EmbeddedResource Include="../../assets/alarm/siren-noise.wav" LogicalName="OpenYI.SirenNoise.wav" />
    <Content Include="../../assets/alarm/LICENSE.md" Link="assets/alarm/LICENSE.md" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Product>OpenYI</Product>
    <Title>OpenYI</Title>
  </PropertyGroup>

</Project>
