<Project>
  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>YI Local contributors</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
